import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from './entities/user.entity';
import { ImportUsersDto } from './dto/import-users.dto';
import { PaginationDto } from './dto/pagination.dto';
import { ChatDto } from './dto/chat.dto';

@Injectable()
export class UsersService {
  constructor(
    @InjectRepository(User)
    private usersRepository: Repository<User>,
  ) {}

  async findAll(pagination: PaginationDto = { page: 1, limit: 10 }) {
    const { page, limit } = pagination;
    const skip = (page! - 1) * limit!;

    const [data, total] = await this.usersRepository.findAndCount({
      order: { createdAt: 'DESC' },
      skip,
      take: limit,
    });

    return {
      data,
      meta: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit!),
        hasNext: page! < Math.ceil(total / limit!),
        hasPrevious: page! > 1,
      },
    };
  }

  async importUsers(dto: ImportUsersDto) {
    const users = dto.rows!.map((row) =>
      this.usersRepository.create({
        name: row.name,
        email: row.email,
        phone: row.phone,
        city: row.city,
        companyPosition: row.companyPosition,
        onERMIS: row.onERMIS || 'No',
        contactPerson: row.contactPerson,
        previousCourses: row.previousCourses,
        notifications: row.notifications,
      }),
    );

    return this.usersRepository.save(users);
  }

  async clearAll() {
    return this.usersRepository.clear();
  }

  async chatWithData(dto: ChatDto) {
    const users = await this.usersRepository.find({
      take: 50,
      order: { createdAt: 'DESC' },
    });

    const userSummary =
      users.length > 0
        ? users.map((u) => ({
            name: u.name,
            email: u.email,
            city: u.city,
            onERMIS: u.onERMIS,
            companyPosition: u.companyPosition,
            notifications: u.notifications,
          }))
        : [];

    const prompt = `
You are a data analysis assistant.

You MUST follow these rules when answering:
- Always format responses in Markdown
- Use tables whenever you present structured data
- Keep answers clean and readable
- Avoid long paragraphs
- Use bullet points when needed

If data is tabular, ALWAYS respond like this:

| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| value 1  | value 2  | value 3  |

Current data summary:
- Total users: ${users.length}
- Sample users: ${JSON.stringify(userSummary.slice(0, 15))}

User question: ${dto.message}

Return only well-formatted Markdown.
`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
        }),
      },
    );

    const data = await response.json();

    console.log('RAW GEMINI RESPONSE:', JSON.stringify(data, null, 2));

    if (data?.error) {
      return {
        reply: `Gemini error: ${data.error.message}`,
        agent: dto.agent || 'gemini',
      };
    }

    if (data?.promptFeedback?.blockReason) {
      return {
        reply: `Blocked request: ${data.promptFeedback.blockReason}`,
        agent: dto.agent || 'gemini',
      };
    }

    const candidate = data?.candidates?.[0];

    if (!candidate) {
      return {
        reply: 'No response generated by Gemini.',
        agent: dto.agent || 'gemini',
      };
    }

    const text =
      candidate?.content?.parts?.map((p: any) => p.text).join('') ||
      'Empty response';

    return {
      reply: text,
      agent: dto.agent || 'gemini',
    };
  }
}
